Make Visitor class more type safe
projectfluent/fluent-kotlin pull request #34
Opened 2020-06-24 11:02 UTC by MikkCZ

Today I had a look at the Visitor class. This PR mainly reduced the number of reflection calls, as they tend to be really slow when used extensively.

There is actually an option to avoid reflection completely, by implementing the [visitor pattern](https://www.baeldung.com/java-visitor-pattern). I will leave up to you whether it's worth it, it would mean to repeat `fun visit(visitor: Visitor) = visitor.visit(this)` in BaseNode and each and every of its sub-classes you want to be supported for specific `visit` implementation. That's because Java linking is static, while the actual type is known only in runtime.

2020-06-24 12:14 UTC, Pike reviewed
Thanks for keeping the PRs coming.

I've got a few nits inline, but also some more general concerns.

One is about having code in the ast package. The `properties` code is effectively the same comment that Stas made in #26.

I'm still concerned about important functionality in a package that doesn't like to be documented.

The other question I have is about the caches and thread-safety. When I mentioned that I'm not concerned about thread-safety, that was on the level of AST instances. I only ever see a single thread manipulating a particular instance of an AST. On a global class level, though, I think we need to be thread-safe.

Which leads me to the question, are the caches for props and handlers thread-safe?

2020-06-24 12:14 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +    fun visitProperties(node: BaseNode) {
This method is called `genericVisit` in all other implementations, I'd like to keep that name consistent to make the resulting code easier to understand across platforms.

2020-06-24 12:14 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +        val handler = handlers(this::class)[node::class]
I struggled to use `::class` from Java. Or maybe just from the Java 7 project that I didn't push yet. Or maybe that was me doing other mistakes. I just remember that this didn't work as expected, though the current tests don't fail.

2020-06-24 12:14 UTC, Pike commented on fluent.syntax/src/test/kotlin/org/projectfluent/syntax/visitor/VisitorTest.kt
> +private class TestableVisitor : Visitor() {
Let's not make this private. I'm not a fan of writing tests in ways that are not going to work in the wild.

This one took me ages to figure out for sure when I tried to write a visitor outside of the fluent package.

2020-06-24 12:14 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +                        .filter { it.parameterCount == 1 && it.parameterTypes[0].kotlin.isSubclassOf(BaseNode::class) }
I think a mismatched signature should be fatal.

I wonder if we should enforce that they're actually taking the concrete node class as parameter.

2020-06-24 13:18 UTC, MikkCZ commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +        val handler = handlers(this::class)[node::class]
There might be issues when you happen to use Kotlin vs. Java classes, or when you happen to use multiple classloader for some reason. If you consider strings to be safer, I revert to that behvaiour. The main idea was to use class to identify the right handler method instead of its name.

2020-06-24 13:20 UTC, MikkCZ commented on fluent.syntax/src/test/kotlin/org/projectfluent/syntax/visitor/VisitorTest.kt
> +private class TestableVisitor : Visitor() {
If you expect to use it outside this test file, I will move it to a standalone file.

2020-06-24 13:25 UTC, MikkCZ commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +                        .filter { it.parameterCount == 1 && it.parameterTypes[0].kotlin.isSubclassOf(BaseNode::class) }
You mean to check that the name matches the signature (i.e. `visitMyNode` accepts `MyNode` and not `SomeOtherNode`)? Definitely, that could be done. But I wouldn't there any more extra logic than that, otherwise the overhead of handling the reflection would quickly overweight the benefits, and that I would argue for implementing the visitor pattern mentioned in the comment above, even if that would have to be via extension functions to not pollute the AST package.

2020-06-24 13:25 UTC, MikkCZ commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +    fun visitProperties(node: BaseNode) {
Consider it done.

2020-06-24 13:36 UTC, MikkCZ commented
Regarding not polluting the AST package, with logic, it's there mostly because the reflection of `equals`, it's caching and possibility to reuse for any other tooling, that needs to read the object's properties (relaxing on the language typing system). It can be moved somewhere else, however that would mean to ban using `equals`, which would produce unexpected behaviour.

On the other hand, looking at the `equals` implementation now, the only reason to have it is to be able to ignore some node implementation specific properties. When called with empty set of ignore properties, it's equivalent to how `data` classes are compared in Kotlin, just much slower this way. And except how the collections and handled, which as implemented now, allows to a `Set` be equals with a `List`, which normally is not allowed.

2020-06-24 16:49 UTC, MikkCZ commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +        val handler = handlers(this::class)[node::class]
Done.

2020-06-24 16:49 UTC, MikkCZ commented on fluent.syntax/src/test/kotlin/org/projectfluent/syntax/visitor/VisitorTest.kt
> +private class TestableVisitor : Visitor() {
Done.

2020-06-24 16:49 UTC, MikkCZ commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/visitor/Visitor.kt
> +                        .filter { it.parameterCount == 1 && it.parameterTypes[0].kotlin.isSubclassOf(BaseNode::class) }
Done.

2020-06-24 16:49 UTC, MikkCZ commented
The concurrency of the reflection caches should be ensured now as well.

2022-07-11 10:33 UTC, Pike requested changes
I'll mark this as "request changes" because this needs another reviewer, and I'd like to get this off my list of PRs to review.

2022-11-28 13:53 UTC, closed without merging