Pattern Processor
projectfluent/fluent-kotlin pull request #42
Opened 2020-09-11 09:40 UTC by stasm

This is a continuation of #40. It adds a `Processor` class with two methods:

- `unescapeLiteralsToText` will bake string literals into surrounding `TextElements`,
- `escapeTextToLiterals` will do the reverse for characters which are special in Fluent syntax (e.g. `{` and `}`).

2020-09-11 13:30 UTC, Pike commented
The idea about a separate data structure didn't work out? I'm not particularly opinionated, but if you can share what made you shift gears, that'd be interesting.

I've started looking at the patch, and docs and comments would help a lot, to tell what's in scope and what's not.

I saw in the tests that you process text inside select expressions, and I'm wondering if that's a good idea. Do we have a use-case for that?

2020-09-22 16:21 UTC, stasm commented
> The idea about a separate data structure didn't work out? I'm not particularly opinionated, but if you can share what made you shift gears, that'd be interesting.

The main reason behind the decision to go with the Fluent AST was that it's already well-documented and has tools that allow working with it. Any new structure would mean new docs and likely new tools. It would also have a higher risk of becoming vendor-specific. 

I experimented with subclassing `Pattern` to make it explicit that it's a different kind of a pattern, one which may not be safely serialized without first un-processing it. However, to make this work, I'd need to either replicate the whole hierachy of `Pattern` → `Placeable` → `SelectExpression` → `Variant` → `Pattern`, or use casting. Casting seemed a bit arbitrary, and in fact not very different from just going with the actual Fluent AST, so I did that instead.

> I've started looking at the patch, and docs and comments would help a lot, to tell what's in scope and what's not.

Sorry for the PR being scarce on docs. I'll work on it.

> I saw in the tests that you process text inside select expressions, and I'm wondering if that's a good idea. Do we have a use-case for that?

I'd like the processing logic to be agnostic wrt. how variant permutations are handled. The expected way of handling them is through "exploding" all permutations into independent translation units, and this can happen after a pattern is processed. Does that answer your question?

2020-09-23 10:53 UTC, Pike commented
> > I saw in the tests that you process text inside select expressions, and I'm wondering if that's a good idea. Do we have a use-case for that?
> 
> I'd like the processing logic to be agnostic wrt. how variant permutations are handled. The expected way of handling them is through "exploding" all permutations into independent translation units, and this can happen after a pattern is processed. Does that answer your question?

Maybe. It's another thing to think about during the review.

Also, in the case of a shall-not-explode string, we should make sure that we're exposing the untransformed message content, and not the transformed one. At least I think so, as the transformed one would be hard to round-trip, right?

2020-09-23 15:04 UTC, stasm commented
> Also, in the case of a shall-not-explode string, we should make sure that we're exposing the untransformed message content, and not the transformed one. At least I think so, as the transformed one would be hard to round-trip, right?

Can you rephrase this, please? What is a _shall-not-explode_ string, and expose to whom? :)

2020-09-23 15:45 UTC, Pike commented
There are messages that some l10n tools may choose to not explode, but show to localizers as plain syntax instead. They should show the original message source, and not a transformed message source. At least that'd be my expectation.

2020-09-23 16:28 UTC, stasm commented
Hmm, interesting. If a message is `key = Hello, {"{-_-}"}.`, my understanding is that it doesn't require exploding, and that a text-oriented editor should display its value processed, as `Hello, {-_-}.` If I understand correctly, that's not what you'd expect?

2020-09-23 17:02 UTC, stasm commented
I added docstrings in the latest commit. I hope they help with the review!

2020-09-24 12:45 UTC, Pike requested changes
Nice docs, I think the majority of it should be on a page in the docs folder, though. I'd like to see the docstrings focus on just a tldr. I locally looked at the tooltips in IDEA on the test, and that's a screenful ;-).

Some review comments I left inline are my fault, sorry for that. It'd still be good to clean those up.
I also recognized that I left quite a few local variables that are useful when debugging, but don't help the code in readability. Not a  big one, though.

2020-09-24 12:45 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                    for (i in element.value.indices) {
If you declare the index outside of the loop, can you drop the `endIndex`, and just use `index + 1` afterwards?

2020-09-24 12:45 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                            }
Same here as for the variants above.

2020-09-24 12:45 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +private val special =
Can we put this and `unescape` next to each other?

Also, this doesn't handle `\U123456` yet. I know it's my fault for not doing so initially, but good to call out.

2020-09-24 12:45 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +            val d = a.toString()
I've had these to step through in the debugger, these should be removed now.

2020-09-24 12:45 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                        is NumberLiteral -> {
The `NumberLiteral` handling doesn't have tests and docs yet?

2020-09-24 12:45 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                            }
I bet the variants can be written as a sequence and `.toMutableList()`, but I don't know how exactly.

2020-09-24 12:45 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +        for (elem in textFromLiterals(pattern)) {
Both here and below, you can probably use `result.elements.addAll(textFromLiterals(pattern))`?

2020-09-24 16:25 UTC, stasm commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +private val special =
I moved `val special` into the class body, and I filed #44 for the `\U123456` case.

2020-09-24 16:27 UTC, stasm commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                            }
Let's keep this as-is, then. Boring code is good :)

2020-09-24 16:32 UTC, stasm commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                    for (i in element.value.indices) {
I think so, but I think it wouldn't work with `value.indices` then?

2020-09-24 16:39 UTC, stasm commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +        for (elem in textFromLiterals(pattern)) {
I think I prefer the good old `for` loop, unless there are functional differences?

2020-09-25 10:50 UTC, Pike requested changes
Thanks for the docs, I built and reviewed them locally.

There's a few small things still, and I've changed my mind on the `NumberLiteral` thing. Which is good, as it means less docs and tests to do ;-) I think we should just let them go through the processor unchanged.

2020-09-25 10:50 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +            val b = a.toChar()
`a` and `b` are also unused.

2020-09-25 10:50 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                    for (i in element.value.indices) {
On a second thought, you don't need  `endIndex` at all, as it's always `element.value.lastIndex + 1`

2020-09-25 10:50 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                    if (endIndex > startIndex) {
`element.value.lastIndex >= startIndex` here, and then just `substring(startIndex)` below.

2020-09-25 10:50 UTC, Pike commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                        is NumberLiteral -> {
I'm leaning towards actually keeping  `NumberLiteral`s in the processed pattern, and mark it up as protected placeable.

Rationale  being that `{20000}`  renders differently in different locales, and is different to `20000` in most languages?

2020-09-25 11:21 UTC, stasm commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +            val b = a.toChar()
D'oh, of course they are, thanks :)

2020-09-25 11:24 UTC, stasm commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                    for (i in element.value.indices) {
Oh, you're right, nice!

2020-09-25 11:26 UTC, stasm commented on fluent.syntax/src/main/kotlin/org/projectfluent/syntax/processor/Processor.kt
> +                        is NumberLiteral -> {
This is a good insight, thanks. I agree, let's leave them in.

2020-09-25 11:56 UTC, Pike approved these changes
Sweet, thanks for taking this. r=me.

2020-09-25 12:01 UTC, merged